apiVersion: v1
kind: ReplicationController
metadata:
  name: hello
  labels:
    name: hello
spec:
  replicas: 1
  selector:
    name: hello
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
      - image: hello:0.0.1
        name: hello
        ports:
        - containerPort: 8080
        resources: {}
      nodeName: node1
