apiVersion: v1
kind: Service
metadata:
  labels:
    name: hello
  name: hello
spec:
  ports:
  - port: 8080
#    protocol: TCP
#    targetPort: 8080
    nodePort: 30008
  selector:
    name: hello
  type: NodePort

  # NodePort 表示Node上的物理机端口提供对外的访问的能力。 nodePort对外访问的端口

