apiVersion: v1
kind: Pod
metadata:
  name: redis-master
  namespace: redis-namespace
spec:
     containers:
      - name: master
        image: kubeguide/redis-master
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: "/data"
            name: "persistent-storage"