apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  replicas: 1
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      volumes:
        - name: "persistent-storage"
          hostPath:
            path: "/data"
      containers:
      - name: master
        image: kubeguide/redis-master
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: "/data"
            name: "persistent-storage"